### PR TITLE
Patch for the latest version of knitr

### PR DESCRIPTION
**Pull request by LTLA**
Some filler text because Github doesn't let me make the PR otherwise.

### CODE REVIEW

**Comment by LTLA** [comment]
Oh, and 3b00a79 will probably also need to be `cherry-pick`ed into `RELEASE_3_11`.

**Comment by LTLA** [comment]
Should be fine with the forced **knitr** version, where the above condition would be `FALSE` all the time anyway.

**Comment by aoles** [comment]
LGTM, thanks a lot @LTLA for the fix!

**Comment by aoles** [comment]
> Oh, and [3b00a79](https://github.com/Bioconductor/BiocStyle/commit/3b00a791973576b724e353d5e29cc42db494cd4c) will probably also need to be `cherry-pick`ed into `RELEASE_3_11`.

Right, but probably only together with `knitr (>= 1.30)` in DESCRIPTION.

**Pull request merged**
