### PR TITLE
Addition of two new functions

### PR DESCRIPTION
**Pull request by Kayla-Morrell**
- `use_vignette_rmd()` to create a skeleton Rmd vignette file
- `use_vignette_pdf()` to create a skeleton pdf vignette file

When these functions are called, a vignette file will be created that contains the skeleton for the vignette. These skeletons come from the templates within BiocStyle. It is the hope that these functions will help limit the number of wrongly formatted vignette files, mostly having to do with the metadata information.

### CODE REVIEW

**Comment by aoles** [comment]
Nice work, thank you for your contribution!

These additions seem to be similar to the functionality already provided by rmarkdown `draft` function. In fact, the following results in the same file as a call to `use_vignette_rmd("MyVignette")`.

```r
rmarkdown::draft("MyVignette.Rmd", template = "html_document", package = "BiocStyle")
```

Therefore, I would rather refrain from duplicating existing functionality. Instead, how about looking into improving the documentation to point to the use of `draft` and the [R Markdown templates menu](https://bookdown.org/yihui/rmarkdown/document-templates.html) from RStudio's GUI as entry points for creating new vignettes?

image

If there is still need of providing additional shortcut functions I would advise to implement them as simple wrappers to `rmarkdown::draft` named as `draft_html_vignette` and `draft_pdf_vignette`. The label `vignette_rmd` might be somehow confusing as Rmd is the input for both HTML and PDF vignettes. Typically you can produce either format from the same Rmd source file by simply changing `output` in the YAML header.

Cheers,
Andrzej

**Comment by mtmorgan** [comment]
Personally I like the idea of something like `BiocStyle::use_vignette_rmd()` --- I know about the RStudio template but don't use RStudio; I'm also familiar, from use devtools etc., with `usethis::use_vignette()`. I would never have been able to come up with the `rmarkdown::draft()` solution, and would always have to look up the documentation instead of just using it...

**Comment by aoles** [comment]
Thanks for your feedback @mtmorgan ! I agree that there is certain value in `use_vignette()`-type convenience functions. On the technical side I strongly advise to implement these functions on top of the functionality offered by rmarkdown. The reason behind this is simplicity and robustness: `rmarkdown::draft` copies not only the bare Rmd skeleton but any supporting files too such as graphics etc. As already pointed out, be careful with the names - I'm still not sure whether `BiocStyle::use_vignette_rmd()` is the optimal choice..

**Comment by Kayla-Morrell** [comment]
Thank you both @aoles and @mtmorgan for your feedback. I have made some changes to my initial code that I hope will satisfy your concerns. Please let me know if there is anything else I could do to help improve these functions.

Best,
Kayla

**Comment by aoles** [comment]
Perfect, thanks again for your contribution!

**Pull request merged**
